spring:
  profiles:
    active: dev

--- # 开发环境
spring:
  profiles:
    active: dev
  application:
    name: reader-springcloud-config-dev

--- # 测试环境
spring:
  profiles:
    active: test
  application:
    name: reader-springcloud-config-test
